============================= test session starts ==============================
platform darwin -- Python 3.11.7, pytest-8.0.1, pluggy-1.4.0
rootdir: /Users/ahaouem/Documents/code/io-http/ed2
collected 0 items / 20 errors

==================================== ERRORS ====================================
___________ ERROR collecting tests/test_respository/test_add_user.py ___________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/test_respository/test_add_user.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_respository/test_add_user.py:1: in <module>
    from repositories import UserRepository
E   ModuleNotFoundError: No module named 'repositories'
___________ ERROR collecting tests/test_respository/test_get_user.py ___________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/test_respository/test_get_user.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_respository/test_get_user.py:1: in <module>
    from repositories import UserRepository
E   ModuleNotFoundError: No module named 'repositories'
_______ ERROR collecting tests/test_respository/test_get_user_failure.py _______
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/test_respository/test_get_user_failure.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_respository/test_get_user_failure.py:1: in <module>
    from repositories import UserRepository
E   ModuleNotFoundError: No module named 'repositories'
_______ ERROR collecting tests/test_respository/test_get_users_empty.py ________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/test_respository/test_get_users_empty.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_respository/test_get_users_empty.py:1: in <module>
    from repositories import UserRepository
E   ModuleNotFoundError: No module named 'repositories'
_______ ERROR collecting tests/test_respository/test_get_users_filled.py _______
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/test_respository/test_get_users_filled.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_respository/test_get_users_filled.py:1: in <module>
    from repositories import UserRepository
E   ModuleNotFoundError: No module named 'repositories'
__________ ERROR collecting tests/test_respository/test_patch_user.py __________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/test_respository/test_patch_user.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_respository/test_patch_user.py:1: in <module>
    from repositories import UserRepository
E   ModuleNotFoundError: No module named 'repositories'
______ ERROR collecting tests/test_respository/test_patch_user_failure.py ______
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/test_respository/test_patch_user_failure.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_respository/test_patch_user_failure.py:1: in <module>
    from repositories import UserRepository
E   ModuleNotFoundError: No module named 'repositories'
_________ ERROR collecting tests/test_respository/test_remove_user.py __________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/test_respository/test_remove_user.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_respository/test_remove_user.py:1: in <module>
    from repositories import UserRepository
E   ModuleNotFoundError: No module named 'repositories'
__ ERROR collecting tests/test_respository/test_user_repository_instantion.py __
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/test_respository/test_user_repository_instantion.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_respository/test_user_repository_instantion.py:1: in <module>
    from repositories import UserRepository
E   ModuleNotFoundError: No module named 'repositories'
___________ ERROR collecting tests/tests_controller/test_add_user.py ___________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_add_user.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_add_user.py:1: in <module>
    from controllers import CreateUserControllerw
E   ModuleNotFoundError: No module named 'controllers'
_ ERROR collecting tests/tests_controller/test_create_user_controller_can_be_instantiated.py _
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_create_user_controller_can_be_instantiated.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_create_user_controller_can_be_instantiated.py:1: in <module>
    from controllers import CreateUserController
E   ModuleNotFoundError: No module named 'controllers'
_________ ERROR collecting tests/tests_controller/test_get_last_id.py __________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_get_last_id.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_get_last_id.py:1: in <module>
    from controllers import CreateUserController
E   ModuleNotFoundError: No module named 'controllers'
___________ ERROR collecting tests/tests_controller/test_get_user.py ___________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_get_user.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_get_user.py:1: in <module>
    from controllers import CreateUserController
E   ModuleNotFoundError: No module named 'controllers'
_______ ERROR collecting tests/tests_controller/test_get_user_failure.py _______
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_get_user_failure.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_get_user_failure.py:1: in <module>
    from controllers import CreateUserController
E   ModuleNotFoundError: No module named 'controllers'
__________ ERROR collecting tests/tests_controller/test_get_users.py ___________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_get_users.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_get_users.py:1: in <module>
    from controllers import CreateUserController
E   ModuleNotFoundError: No module named 'controllers'
__________ ERROR collecting tests/tests_controller/test_patch_user.py __________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_patch_user.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_patch_user.py:1: in <module>
    from controllers import CreateUserController
E   ModuleNotFoundError: No module named 'controllers'
______ ERROR collecting tests/tests_controller/test_patch_user_failure.py ______
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_patch_user_failure.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_patch_user_failure.py:1: in <module>
    from controllers import CreateUserController
E   ModuleNotFoundError: No module named 'controllers'
_________ ERROR collecting tests/tests_controller/test_remove_user.py __________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_remove_user.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_remove_user.py:1: in <module>
    from controllers import CreateUserController
E   ModuleNotFoundError: No module named 'controllers'
_____ ERROR collecting tests/tests_controller/test_remove_user_failure.py ______
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_remove_user_failure.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_remove_user_failure.py:1: in <module>
    from controllers import CreateUserController
E   ModuleNotFoundError: No module named 'controllers'
_________ ERROR collecting tests/tests_controller/test_validate_id.py __________
ImportError while importing test module '/Users/ahaouem/Documents/code/io-http/ed2/tests/tests_controller/test_validate_id.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_controller/test_validate_id.py:1: in <module>
    from controllers import CreateUserController
E   ModuleNotFoundError: No module named 'controllers'
=========================== short test summary info ============================
ERROR tests/test_respository/test_add_user.py
ERROR tests/test_respository/test_get_user.py
ERROR tests/test_respository/test_get_user_failure.py
ERROR tests/test_respository/test_get_users_empty.py
ERROR tests/test_respository/test_get_users_filled.py
ERROR tests/test_respository/test_patch_user.py
ERROR tests/test_respository/test_patch_user_failure.py
ERROR tests/test_respository/test_remove_user.py
ERROR tests/test_respository/test_user_repository_instantion.py
ERROR tests/tests_controller/test_add_user.py
ERROR tests/tests_controller/test_create_user_controller_can_be_instantiated.py
ERROR tests/tests_controller/test_get_last_id.py
ERROR tests/tests_controller/test_get_user.py
ERROR tests/tests_controller/test_get_user_failure.py
ERROR tests/tests_controller/test_get_users.py
ERROR tests/tests_controller/test_patch_user.py
ERROR tests/tests_controller/test_patch_user_failure.py
ERROR tests/tests_controller/test_remove_user.py
ERROR tests/tests_controller/test_remove_user_failure.py
ERROR tests/tests_controller/test_validate_id.py
!!!!!!!!!!!!!!!!!!! Interrupted: 20 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 20 errors in 0.06s ==============================
